export const tableData = [
    {
        name: 'Alice Johnson',
        email: 'alice@example.com',
        role: 'Admin',
        status: 'Active',
    },
    {
        name: 'Bob Smith',
        email: 'bob@example.com',
        role: 'User',
        status: 'Inactive',
    },
    {
        name: 'Charlie Brown',
        email: 'charlie@example.com',
        role: 'Moderator',
        status: 'Active',
    },
    {
        name: 'David Williams',
        email: 'david@example.com',
        role: 'User',
        status: 'Active',
    },
    {
        name: 'Emma Davis',
        email: 'emma@example.com',
        role: 'Admin',
        status: 'Inactive',
    },
    {
        name: 'Frank Miller',
        email: 'frank@example.com',
        role: 'Moderator',
        status: 'Active',
    },
    {
        name: 'Grace Lee',
        email: 'grace@example.com',
        role: 'User',
        status: 'Inactive',
    },
    {
        name: 'Henry Wilson',
        email: 'henry@example.com',
        role: 'Admin',
        status: 'Active',
    },
    {
        name: 'Isla Martinez',
        email: 'isla@example.com',
        role: 'User',
        status: 'Inactive',
    },
    {
        name: 'Jack Taylor',
        email: 'jack@example.com',
        role: 'Moderator',
        status: 'Active',
    },
    {
        name: 'Kate Brown',
        email: 'kate@example.com',
        role: 'User',
        status: 'Active',
    },
    {
        name: 'Leo Thomas',
        email: 'leo@example.com',
        role: 'Admin',
        status: 'Inactive',
    },
    {
        name: 'Mia Scott',
        email: 'mia@example.com',
        role: 'Moderator',
        status: 'Active',
    },
    {
        name: 'Noah Allen',
        email: 'noah@example.com',
        role: 'User',
        status: 'Inactive',
    },
    {
        name: 'Olivia Harris',
        email: 'olivia@example.com',
        role: 'Admin',
        status: 'Active',
    },
    {
        name: 'Paul Young',
        email: 'paul@example.com',
        role: 'User',
        status: 'Inactive',
    },
    {
        name: 'Quinn Adams',
        email: 'quinn@example.com',
        role: 'Moderator',
        status: 'Active',
    },
    {
        name: 'Rachel White',
        email: 'rachel@example.com',
        role: 'Admin',
        status: 'Inactive',
    },
    {
        name: 'Samuel King',
        email: 'samuel@example.com',
        role: 'User',
        status: 'Active',
    },
    {
        name: 'Tina Brooks',
        email: 'tina@example.com',
        role: 'Moderator',
        status: 'Inactive',
    },
];
